"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

def factor_count(N):
  accumulator = 2  # Default includes 1 and N
  for i in range(2, int(N**0.5)):
    if N % i == 0:
      accumulator += 2
  return accumulator

def first_triangle_with_divisors(divisor_count):
  triangle = 0
  i = 1
  while True:
    triangle += i
    i += 1
    if factor_count(triangle) > divisor_count:
      return triangle

def main():
  print(first_triangle_with_divisors(500))

if __name__ == '__main__':
  main()
